image:
  file: .gitpod.dockerfile
tasks:
  - name: PHPMyAdmin
    command: cd /home/gitpod/phpMyAdmin-5.1.3-all-languages && php -S localhost:8080
  - name: Backend
    init: cd packages/server && composer install
    command: php artisan serve
  - name: Frontend
    init: cd packages/app && npm install
    command: npm run dev
