image:
  file: .gitpod.dockerfile

ports:
  - port: 3306
    onOpen: ignore
  - port: 33060
    onOpen: ignore
  - port: 8080
    onOpen: ignore

tasks:
  - name: Backend
    init: |
      cd packages/server
      composer install
      gp await-port 3306 && sleep 3 
      php artisan twill:install --no-interaction
      php artisan twill:superadmin admin@admin.local admin
    command: php artisan serve
  - name: Frontend
    init: |
      cd packages/app
      npm install
    command: npm run dev
  - name: PHPMyAdmin
    init: |
      gp await-port 3306 && sleep 3
      mysqladmin -u root password root
      cd /home/gitpod/phpMyAdmin-5.1.3-all-languages
    command: php -S localhost:8080
